"""
n=4 RAC advantage-space cross-section
======================================

Builds the symmetry-completed 4D polytope generated by the two n=4
vertex classes documented in the RAC Geometry project notes, takes an
arbitrary 3D affine cross-section,

    SLICE_NORMAL · c = SLICE_OFFSET,

and renders that section with PyVista.

Dependencies
------------
pip install numpy scipy pyvista

Scope
-----
The project notes document two n=4 vertex classes for the optimal
classical tie-strategy structure:

    degree type (3,1,1,1)  -> advantage prototype (3,1,1,1)/4
    degree type (2,2,2,0)  -> advantage prototype (2,2,2,0)/4

This script closes those prototypes under coordinate permutations and
independent sign flips, then takes their convex hull.

It therefore visualizes the symmetry-completed polytope generated by
those documented n=4 vertex classes. It should not be read, without an
additional proof, as an enumeration of every vertex of the completely
unrestricted one-bit classical RAC body.
"""

from __future__ import annotations

from itertools import permutations, product
from time import perf_counter

import numpy as np
import pyvista as pv
from scipy.linalg import null_space
from scipy.spatial import ConvexHull


# ============================================================================
# USER SETTINGS
# ============================================================================

# ----------------------------------------------------------------------------
# CROSS-SECTION
# ----------------------------------------------------------------------------

# Hyperplane equation:
#
#     SLICE_NORMAL · c = SLICE_OFFSET
#
# Examples:
#
# c4 = 0:
# SLICE_NORMAL = np.array([0.0, 0.0, 0.0, 1.0])
# SLICE_OFFSET = 0.0
#
# Perpendicular to RAC winning direction:
# SLICE_NORMAL = np.array([1.0, 1.0, 1.0, 1.0])
# SLICE_OFFSET = 0.0
#
# Tilted slice:
# SLICE_NORMAL = np.array([1.0, 1.0, 0.0, 0.5])
# SLICE_OFFSET = 0.20

SLICE_NORMAL = np.array([1.0, 0.0, 0.0, 0.0])
SLICE_OFFSET = 0.0


# ----------------------------------------------------------------------------
# OBJECT APPEARANCE
# ----------------------------------------------------------------------------

OPACITY = 1.0

SHOW_EDGES = True
EDGE_WIDTH = 1.5

# Draw only edges where adjacent surface triangles meet at a real angle.
# This suppresses triangulation diagonals within a flat polygonal face.
FEATURE_ANGLE = 2.0  # degrees (legacy; planar-face edge extraction does not use this)

# Tolerances used to merge Qhull's triangulated facets back into their
# underlying polygonal faces before drawing edges.
#
# Two triangles are considered part of the same planar face when their
# unit normals and plane offsets agree within these tolerances.
COPLANAR_NORMAL_TOL = 1e-7
COPLANAR_OFFSET_TOL = 1e-7

SHOW_SECTION_VERTICES = False
SECTION_VERTEX_SIZE = 8
SHOW_ORIGINAL_VERTICES = True
ORIGINAL_VERTEX_SIZE = 18
SHOW_PROJECTED_AXES = False
AXIS_LENGTH = 1.15
SHOW_WINNING_DIRECTION = False
WINNING_DIRECTION_LENGTH = 1.35

SMOOTH_SHADING = False

# Leave as None to let PyVista choose its normal default material color.
# Example:
# OBJECT_COLOR = "lightblue"
OBJECT_COLOR = None

# Example:
# EDGE_COLOR = "black"
EDGE_COLOR = None


# ----------------------------------------------------------------------------
# CAMERA
# ----------------------------------------------------------------------------

# Camera location in the displayed 3D slice coordinates.
CAMERA_POSITION = (3.0, 2.0, 1.0)

# Point the camera looks at.
CAMERA_FOCAL_POINT = (0.0, 0.0, 0.0)

# Which direction appears "up" on screen.
CAMERA_UP = (0.0, 0.0, 1.0)

# Use perspective projection by default.
# Set True for orthographic / parallel projection.
PARALLEL_PROJECTION = False

# Useful for consistently zooming a fixed camera.
# 1.0 = unchanged; >1 zooms in; <1 zooms out.
CAMERA_ZOOM = 1.0

# ----------------------------------------------------------------------------
# AXIS INSET
# ----------------------------------------------------------------------------
#
# The axes that actually lie in the selected cross-section are drawn as a
# translated 3D inset next to the polytope. They live in the SAME PyVista
# renderer, so the polytope and the inset use exactly the same camera,
# perspective and projection.
#
# Inset position is camera-relative: +RIGHT moves it right on screen,
# +UP moves it upward, +DEPTH moves it toward the camera.

SHOW_AXIS_INSET = True
AXIS_INSET_RIGHT = 1.55
AXIS_INSET_UP = 0.15
AXIS_INSET_DEPTH = 0.0

AXIS_INSET_LENGTH = 0.70
AXIS_INSET_SHAFT_RADIUS = 0.010
AXIS_INSET_TIP_LENGTH = 0.16
AXIS_INSET_TIP_RADIUS = 0.040
AXIS_INSET_LABEL_SCALE = 1.10
AXIS_INSET_ORIGIN_SIZE = 12
AXIS_INSET_SHOW_PANEL = True
AXIS_INSET_PANEL_WIDTH = 2.10
AXIS_INSET_PANEL_HEIGHT = 1.55
AXIS_INSET_PANEL_BACK = 0.08
AXIS_INSET_PANEL_OPACITY = 0.92
AXIS_INSET_PANEL_COLOR = "white"
AXIS_INSET_PANEL_EDGE_COLOR = "steelblue"

AXIS_COLORS = ("red", "green", "blue", "purple")


# ----------------------------------------------------------------------------
# LIGHTING
# ----------------------------------------------------------------------------

# If True, disable PyVista's default lights and use the custom lights below.
USE_CUSTOM_LIGHTING = True

# Main/key light
LIGHT_POSITION = (4.0, 3.0, 5.0)
LIGHT_FOCAL_POINT = (0.0, 0.0, 0.0)
LIGHT_INTENSITY = 1.0

# Fill light to soften the dark side of the polytope.
USE_FILL_LIGHT = True
FILL_LIGHT_POSITION = (-3.0, -2.0, 2.0)
FILL_LIGHT_FOCAL_POINT = (0.0, 0.0, 0.0)
FILL_LIGHT_INTENSITY = 0.35


# ----------------------------------------------------------------------------
# SCENE / OUTPUT
# ----------------------------------------------------------------------------

WINDOW_SIZE = (1100, 900)

BACKGROUND = "white"

SHOW_AXES = False
SHOW_LEGEND = True
SHOW_TITLE = True

# Set to None for interactive window only.
# Example:
# SCREENSHOT = "n4_slice.png"
SCREENSHOT = None

# Set True to print the full list of section vertices in original 4D coordinates.
PRINT_SECTION_VERTICES = True

# Numerical tolerance
TOL = 1e-10


# ============================================================================
# n=4 POLYTOPE
# ============================================================================

PROTOTYPES = (
    np.array([3.0, 1.0, 1.0, 1.0]) / 4.0,
    np.array([2.0, 2.0, 2.0, 0.0]) / 4.0,
    np.array([1.0, 0.0, 0.0, 0.0]),
)


def log(msg: str) -> None:
    print(msg, flush=True)


def unique_rows(points: np.ndarray, decimals: int = 10) -> np.ndarray:
    """Remove duplicate rows using rounded coordinates."""
    points = np.asarray(points, dtype=float)
    rounded = np.round(points, decimals)
    _, idx = np.unique(rounded, axis=0, return_index=True)
    return points[np.sort(idx)]


def symmetry_orbit(prototype: np.ndarray) -> np.ndarray:
    """
    Generate coordinate permutations and independent coordinate sign flips.
    """
    points = []

    for perm in set(permutations(prototype.tolist())):
        p = np.asarray(perm, dtype=float)

        for signs in product((-1.0, 1.0), repeat=4):
            points.append(p * np.asarray(signs, dtype=float))

    return unique_rows(np.asarray(points))


def build_vertices() -> np.ndarray:
    """Return all symmetry-completed generating points."""
    points = np.vstack([symmetry_orbit(p) for p in PROTOTYPES])
    return unique_rows(points)


# ============================================================================
# 4D -> 3D CROSS-SECTION
# ============================================================================

def slice_basis(
    normal: np.ndarray,
    offset: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Construct an orthonormal 3D coordinate system inside

        normal · x = offset.

    Returns
    -------
    n_hat
        Normalized hyperplane normal.
    x0
        Point on the hyperplane closest to the origin.
    basis
        4x3 orthonormal matrix spanning the hyperplane.
    """
    normal = np.asarray(normal, dtype=float)

    if normal.shape != (4,):
        raise ValueError("SLICE_NORMAL must have exactly four components.")

    length = np.linalg.norm(normal)

    if length < TOL:
        raise ValueError("SLICE_NORMAL cannot be the zero vector.")

    n_hat = normal / length
    d = float(offset) / length

    x0 = d * n_hat
    basis = null_space(n_hat.reshape(1, 4))

    if basis.shape != (4, 3):
        raise RuntimeError("Could not construct the 3D slice basis.")

    return n_hat, x0, basis


def candidate_edges_from_hull(hull: ConvexHull) -> list[tuple[int, int]]:
    """
    Extract candidate boundary edges from Qhull's triangulated 4D facets.

    Some candidates can be diagonals inside a non-simplicial facet.
    That is harmless: their intersection points disappear when we take
    the final 3D convex hull.
    """
    edges = set()

    for simplex in hull.simplices:
        for i in range(len(simplex)):
            for j in range(i + 1, len(simplex)):
                a, b = sorted((int(simplex[i]), int(simplex[j])))
                edges.add((a, b))

    return sorted(edges)


def section_points_from_edges(
    vertices: np.ndarray,
    edges: list[tuple[int, int]],
    normal: np.ndarray,
    offset: float,
) -> np.ndarray:
    """
    Intersect candidate hull edges with

        normal · x = offset.
    """
    signed_distance = vertices @ normal - offset
    points = []

    for i, j in edges:
        vi = vertices[i]
        vj = vertices[j]

        fi = signed_distance[i]
        fj = signed_distance[j]

        # Entire candidate edge lies in the plane.
        if abs(fi) <= TOL and abs(fj) <= TOL:
            points.extend((vi, vj))
            continue

        # One endpoint lies in the plane.
        if abs(fi) <= TOL:
            points.append(vi)
            continue

        if abs(fj) <= TOL:
            points.append(vj)
            continue

        # Edge crosses the plane.
        if fi * fj < 0.0:
            t = fi / (fi - fj)
            point = vi + t * (vj - vi)
            points.append(point)

    if not points:
        raise ValueError(
            "The selected hyperplane does not intersect the 4D polytope."
        )

    return unique_rows(np.asarray(points), decimals=9)


def to_slice_coordinates(
    points_4d: np.ndarray,
    x0: np.ndarray,
    basis: np.ndarray,
) -> np.ndarray:
    """Express R^4 points in the slice's 3D orthonormal coordinates."""
    return (points_4d - x0) @ basis


def compute_section(
    vertices: np.ndarray,
    normal: np.ndarray,
    offset: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, ConvexHull]:
    """Compute the 3D cross-section and return its vertices and hull."""

    t0 = perf_counter()

    log("[1/5] Computing 4D convex hull...")
    hull4 = ConvexHull(vertices)

    log(
        f"      done: {len(vertices)} generating points, "
        f"{len(hull4.simplices)} triangulated boundary facets "
        f"({perf_counter() - t0:.3f} s)"
    )

    t1 = perf_counter()

    log("[2/5] Extracting candidate hull edges...")
    edges = candidate_edges_from_hull(hull4)

    log(
        f"      done: {len(edges)} candidate edges "
        f"({perf_counter() - t1:.3f} s)"
    )

    t2 = perf_counter()

    log("[3/5] Intersecting edges with 3D slice...")
    points4 = section_points_from_edges(
        vertices,
        edges,
        normal,
        offset,
    )

    log(
        f"      done: {len(points4)} unique intersection points "
        f"({perf_counter() - t2:.3f} s)"
    )

    _, x0, basis = slice_basis(normal, offset)
    points3 = to_slice_coordinates(points4, x0, basis)

    t3 = perf_counter()

    log("[4/5] Computing 3D convex hull of the section...")
    hull3_initial = ConvexHull(points3)

    # Remove candidate intersection points that are not actual hull vertices.
    surface_ids = np.unique(hull3_initial.simplices.ravel())
    points3_surface = points3[surface_ids]
    points4_surface = points4[surface_ids]

    hull3 = ConvexHull(points3_surface)

    log(
        f"      done: {len(points3_surface)} actual section vertices, "
        f"{len(hull3.simplices)} surface triangles "
        f"({perf_counter() - t3:.3f} s)"
    )

    return points3_surface, points4_surface, basis, hull3




# ============================================================================
# GEOMETRY ANNOTATIONS
# ============================================================================

VERTEX_TYPE_PROTOTYPES = {
    "axis type (1,0,0,0)": np.array([1.0, 0.0, 0.0, 0.0]),
    "3/4 + 1/4 type": np.array([0.75, 0.25, 0.25, 0.25]),
    "1/2 + 1/2 + 1/2 type": np.array([0.5, 0.5, 0.5, 0.0]),
}

VERTEX_TYPE_COLORS = {
    "axis type (1,0,0,0)": "crimson",
    "3/4 + 1/4 type": "royalblue",
    "1/2 + 1/2 + 1/2 type": "darkorange",
}

def canonical_abs_sorted(v):
    return np.sort(np.abs(np.asarray(v, dtype=float)))[::-1]

def classify_original_vertex(v):
    target = canonical_abs_sorted(v)
    for name, proto in VERTEX_TYPE_PROTOTYPES.items():
        if np.allclose(target, canonical_abs_sorted(proto), atol=1e-8, rtol=0.0):
            return name
    return None

def project_direction_to_slice(direction4, normal, basis):
    d = np.asarray(direction4, dtype=float)
    projected4 = d - np.dot(d, normal) * normal
    nrm = np.linalg.norm(projected4)
    if nrm < 1e-8:
        return None
    projected4 /= nrm
    d3 = projected4 @ basis
    d3 /= np.linalg.norm(d3)
    return d3

def add_arrow(plotter, direction3, length, label, color):
    arrow = pv.Arrow(start=(0,0,0), direction=direction3, scale=length)
    plotter.add_mesh(arrow, color=color)
    pos = np.asarray(direction3) * length * 1.08
    plotter.add_point_labels(np.asarray([pos]), [label], point_size=0, font_size=16,
                             always_visible=True, shape=None, text_color=color)

def add_projected_axes(plotter, normal, basis):
    colors = ("red", "green", "blue", "purple")
    for i in range(4):
        e = np.zeros(4); e[i] = 1.0
        d3 = project_direction_to_slice(e, normal, basis)
        if d3 is None:
            log(f"      c{i+1} is perpendicular to the slice; not drawn.")
            continue
        add_arrow(plotter, d3, AXIS_LENGTH, f"c{i+1}", colors[i])

def add_winning_direction(plotter, normal, basis):
    d3 = project_direction_to_slice(np.ones(4), normal, basis)
    if d3 is None:
        log("      Winning direction is perpendicular to the slice; not drawn.")
        return
    add_arrow(plotter, d3, WINNING_DIRECTION_LENGTH, "winning direction", "black")

def add_original_vertices(plotter, vertices4, normal, offset, x0, basis):
    mask = np.abs(vertices4 @ normal - offset) <= 1e-8
    verts = vertices4[mask]
    if len(verts) == 0:
        log("      No genuine original 4D vertices lie in this slice.")
        return
    for name, color in VERTEX_TYPE_COLORS.items():
        sel = [v for v in verts if classify_original_vertex(v) == name]
        if not sel:
            continue
        pts3 = to_slice_coordinates(np.asarray(sel), x0, basis)
        plotter.add_mesh(pv.PolyData(pts3), color=color, point_size=ORIGINAL_VERTEX_SIZE,
                         render_points_as_spheres=True, label=name)


def camera_frame(plotter):
    """
    Return orthonormal camera-relative directions in slice coordinates.

    right      : screen-right
    screen_up  : screen-up
    toward_cam : from the focal point toward the camera
    """
    position = np.asarray(plotter.camera.position, dtype=float)
    focal = np.asarray(plotter.camera.focal_point, dtype=float)
    up_hint = np.asarray(plotter.camera.up, dtype=float)

    view = focal - position
    view /= np.linalg.norm(view)

    right = np.cross(view, up_hint)
    right /= np.linalg.norm(right)

    screen_up = np.cross(right, view)
    screen_up /= np.linalg.norm(screen_up)

    toward_cam = -view
    return right, screen_up, toward_cam


def axes_that_lie_in_slice(normal, basis):
    """
    Return the original advantage axes c_i that are tangent to the slice.

    For example, for c1 = 0 this returns c2, c3 and c4.  These are mapped
    into the SAME 3D slice coordinate system as the polytope, so their
    screen projection is controlled by the same camera.
    """
    axes = []
    for i in range(4):
        e4 = np.zeros(4)
        e4[i] = 1.0

        # e_i lies in n·x=offset iff n·e_i = 0.
        if abs(float(np.dot(normal, e4))) > 1e-8:
            continue

        d3 = e4 @ basis
        nrm = np.linalg.norm(d3)
        if nrm < 1e-10:
            continue

        axes.append((i, d3 / nrm, e4))

    return axes


def add_camera_facing_panel(plotter, center, right, screen_up, toward_cam):
    """Add a subtle camera-facing backing panel behind the inset."""
    if not AXIS_INSET_SHOW_PANEL:
        return

    w = AXIS_INSET_PANEL_WIDTH
    h = AXIS_INSET_PANEL_HEIGHT

    # Put the panel slightly farther away than the arrows to avoid z-fighting.
    c = np.asarray(center) - AXIS_INSET_PANEL_BACK * toward_cam

    corners = np.array([
        c - 0.5*w*right - 0.5*h*screen_up,
        c + 0.5*w*right - 0.5*h*screen_up,
        c + 0.5*w*right + 0.5*h*screen_up,
        c - 0.5*w*right + 0.5*h*screen_up,
    ])

    faces = np.array([4, 0, 1, 2, 3])
    panel = pv.PolyData(corners, faces)
    plotter.add_mesh(
        panel,
        color=AXIS_INSET_PANEL_COLOR,
        opacity=AXIS_INSET_PANEL_OPACITY,
        lighting=False,
        show_edges=True,
        edge_color=AXIS_INSET_PANEL_EDGE_COLOR,
        line_width=1.5,
    )


def add_axis_inset(plotter, normal, basis):
    """
    Draw the actual advantage axes contained in the cross-section.

    Crucially, this is NOT a second renderer.  The arrows are translated
    geometry inside the same 3D scene, and therefore use exactly the same
    camera, perspective/parallel projection, and viewpoint as the polytope.
    """
    axes = axes_that_lie_in_slice(normal, basis)

    if not axes:
        log("      No original coordinate axis lies exactly in this tilted slice.")
        return

    right, screen_up, toward_cam = camera_frame(plotter)
    focal = np.asarray(plotter.camera.focal_point, dtype=float)

    origin = (
        focal
        + AXIS_INSET_RIGHT * right
        + AXIS_INSET_UP * screen_up
        + AXIS_INSET_DEPTH * toward_cam
    )

    # Panel center is shifted slightly down/right from the arrow origin so
    # there is visual room for labels, similar to the target layout.
    panel_center = origin + 0.30 * right - 0.12 * screen_up
    add_camera_facing_panel(
        plotter, panel_center, right, screen_up, toward_cam
    )

    # Origin marker.
    plotter.add_mesh(
        pv.Sphere(radius=0.025, center=origin),
        color="black",
        lighting=False,
    )

    for i, d3, e4 in axes:
        color = AXIS_COLORS[i]

        # Scale Arrow's shape parameters relative to its unit-length geometry.
        arrow = pv.Arrow(
            start=origin,
            direction=d3,
            tip_length=AXIS_INSET_TIP_LENGTH / AXIS_INSET_LENGTH,
            tip_radius=AXIS_INSET_TIP_RADIUS / AXIS_INSET_LENGTH,
            shaft_radius=AXIS_INSET_SHAFT_RADIUS / AXIS_INSET_LENGTH,
            scale=AXIS_INSET_LENGTH,
        )
        plotter.add_mesh(arrow, color=color, lighting=True)

        tip = origin + d3 * AXIS_INSET_LENGTH
        label_pos = tip + d3 * (0.11 * AXIS_INSET_LABEL_SCALE)

        plotter.add_point_labels(
            np.asarray([label_pos]),
            [f"c{i+1}"],
            point_size=0,
            font_size=int(17 * AXIS_INSET_LABEL_SCALE),
            always_visible=True,
            shape=None,
            text_color=color,
        )

        log(
            f"      inset axis c{i+1}: "
            f"{np.asarray(e4, dtype=int)} -> "
            f"slice direction {np.round(d3, 5)}"
        )

    # Heading is screen-facing text, but its anchor point is in this same scene.
    heading_pos = (
        panel_center
        - 0.43 * AXIS_INSET_PANEL_WIDTH * right
        + 0.42 * AXIS_INSET_PANEL_HEIGHT * screen_up
        + 0.01 * toward_cam
    )
    plotter.add_point_labels(
        np.asarray([heading_pos]),
        ["axes in this cross-section"],
        point_size=0,
        font_size=15,
        bold=True,
        always_visible=True,
        shape=None,
        text_color="black",
    )


def _normalized_hull_planes(hull3: ConvexHull):
    """Return unit facet normals and consistently scaled plane offsets."""
    equations = np.asarray(hull3.equations, dtype=float)
    normals = equations[:, :3].copy()
    offsets = equations[:, 3].copy()

    lengths = np.linalg.norm(normals, axis=1)
    normals /= lengths[:, None]
    offsets /= lengths

    return normals, offsets


def _group_coplanar_triangles(hull3: ConvexHull):
    """
    Group Qhull surface triangles that belong to the same mathematical plane.

    scipy.spatial.ConvexHull triangulates polygonal faces.  Comparing triangle
    normals locally (as vtkFeatureEdges does) can leave false diagonals because
    numerically coplanar triangles are not always represented by exactly equal
    normals.  Here we explicitly merge such triangles first.
    """
    normals, offsets = _normalized_hull_planes(hull3)
    groups = []

    for tri_id, (normal, offset) in enumerate(zip(normals, offsets)):
        matched = False

        for group in groups:
            ref_normal = group["normal"]
            ref_offset = group["offset"]

            # Qhull uses consistently outward-facing normals for a convex hull.
            # The abs fallback makes this robust even if an orientation ever
            # arrives reversed.
            same_orientation = np.linalg.norm(normal - ref_normal) <= COPLANAR_NORMAL_TOL
            opposite_orientation = np.linalg.norm(normal + ref_normal) <= COPLANAR_NORMAL_TOL

            if same_orientation:
                same_plane = abs(offset - ref_offset) <= COPLANAR_OFFSET_TOL
            elif opposite_orientation:
                same_plane = abs(offset + ref_offset) <= COPLANAR_OFFSET_TOL
            else:
                same_plane = False

            if same_plane:
                group["triangles"].append(tri_id)
                matched = True
                break

        if not matched:
            groups.append({
                "normal": normal.copy(),
                "offset": float(offset),
                "triangles": [tri_id],
            })

    return groups


def true_polytope_edges(hull3: ConvexHull) -> list[tuple[int, int]]:
    """
    Recover only boundaries between polygonal faces of the 3D section.

    For each coplanar triangle group, every triangulation diagonal occurs twice
    inside that group, while an edge on the boundary of the polygonal face
    occurs once.  Keeping the once-occurring edges therefore removes all
    diagonals that lie inside a plane.
    """
    groups = _group_coplanar_triangles(hull3)
    true_edges = set()

    for group in groups:
        counts = {}

        for tri_id in group["triangles"]:
            tri = hull3.simplices[tri_id]

            for a, b in (
                (int(tri[0]), int(tri[1])),
                (int(tri[1]), int(tri[2])),
                (int(tri[2]), int(tri[0])),
            ):
                edge = tuple(sorted((a, b)))
                counts[edge] = counts.get(edge, 0) + 1

        # Boundary edges of this planar polygon occur exactly once.
        for edge, count in counts.items():
            if count == 1:
                true_edges.add(edge)

    return sorted(true_edges)


def add_feature_edges(plotter, points3, hull3):
    """
    Draw true polytope edges after merging coplanar hull triangles.

    This deliberately does not use vtk/PyVista feature-angle extraction.
    """
    if not SHOW_EDGES:
        return

    edges = true_polytope_edges(hull3)

    if not edges:
        log("      Warning: no polytope edges were reconstructed.")
        return

    # PyVista line-cell format: [2, i, j, 2, i, j, ...]
    lines = np.asarray(
        [[2, i, j] for i, j in edges],
        dtype=np.int64,
    ).ravel()

    edge_mesh = pv.PolyData(np.asarray(points3, dtype=float))
    edge_mesh.lines = lines

    color = EDGE_COLOR if EDGE_COLOR is not None else "black"
    plotter.add_mesh(
        edge_mesh,
        color=color,
        line_width=EDGE_WIDTH,
        lighting=False,
    )

    log(
        f"      reconstructed {len(_group_coplanar_triangles(hull3))} "
        f"planar faces and {len(edges)} true edges"
    )


# ============================================================================
# PYVISTA RENDERING
# ============================================================================

def make_mesh(
    points3: np.ndarray,
    hull3: ConvexHull,
) -> pv.PolyData:
    """Convert scipy's triangular hull surface to PyVista PolyData."""

    triangles = hull3.simplices.astype(np.int64)

    faces = np.column_stack(
        (
            np.full(len(triangles), 3, dtype=np.int64),
            triangles,
        )
    ).ravel()

    return pv.PolyData(points3, faces)


def configure_lighting(plotter: pv.Plotter) -> None:
    """Apply reproducible custom lighting."""

    if not USE_CUSTOM_LIGHTING:
        return

    plotter.remove_all_lights()

    key_light = pv.Light(
        position=LIGHT_POSITION,
        focal_point=LIGHT_FOCAL_POINT,
        intensity=LIGHT_INTENSITY,
    )
    plotter.add_light(key_light)

    if USE_FILL_LIGHT:
        fill_light = pv.Light(
            position=FILL_LIGHT_POSITION,
            focal_point=FILL_LIGHT_FOCAL_POINT,
            intensity=FILL_LIGHT_INTENSITY,
        )
        plotter.add_light(fill_light)


def configure_camera(plotter: pv.Plotter) -> None:
    """Apply a fixed reproducible camera."""

    plotter.camera.position = CAMERA_POSITION
    plotter.camera.focal_point = CAMERA_FOCAL_POINT
    plotter.camera.up = CAMERA_UP

    if PARALLEL_PROJECTION:
        plotter.enable_parallel_projection()
    else:
        plotter.disable_parallel_projection()

    if CAMERA_ZOOM != 1.0:
        plotter.camera.zoom(CAMERA_ZOOM)



def slice_equation_label(normal, offset):
    """Human-readable hyperplane label for simple coordinate slices."""
    nz = np.flatnonzero(np.abs(normal) > 1e-8)
    if len(nz) == 1 and abs(abs(normal[nz[0]]) - 1.0) < 1e-8:
        i = int(nz[0])
        value = offset / normal[i]
        return f"slice: c{i+1} = {value:g}"
    return f"slice: n·c = {offset:g}"


def plot_section(
    points3: np.ndarray,
    hull3: ConvexHull,
    vertices4: np.ndarray,
    normal: np.ndarray,
    offset: float,
    x0: np.ndarray,
    basis: np.ndarray,
) -> None:
    """Render the section interactively with PyVista."""

    log("[5/5] Opening PyVista window...")
    log("      Close the PyVista window to return to PowerShell.")

    mesh = make_mesh(points3, hull3)
    plotter = pv.Plotter(window_size=WINDOW_SIZE)
    plotter.set_background(BACKGROUND)
    configure_lighting(plotter)

    mesh_kwargs = dict(
        opacity=OPACITY,
        show_edges=False,
        smooth_shading=SMOOTH_SHADING,
        label="n=4 classical section",
    )
    if OBJECT_COLOR is not None:
        mesh_kwargs["color"] = OBJECT_COLOR
    if EDGE_COLOR is not None:
        mesh_kwargs["edge_color"] = EDGE_COLOR
    plotter.add_mesh(mesh, **mesh_kwargs)
    add_feature_edges(plotter, points3, hull3)

    if SHOW_SECTION_VERTICES:
        plotter.add_mesh(pv.PolyData(points3), point_size=SECTION_VERTEX_SIZE,
                         render_points_as_spheres=True, label="section vertices")

    if SHOW_ORIGINAL_VERTICES:
        add_original_vertices(plotter, vertices4, normal, offset, x0, basis)

    if SHOW_PROJECTED_AXES:
        add_projected_axes(plotter, normal, basis)

    if SHOW_WINNING_DIRECTION:
        add_winning_direction(plotter, normal, basis)

    if SHOW_AXES:
        plotter.add_axes(xlabel="slice axis 1", ylabel="slice axis 2", zlabel="slice axis 3")

    if SHOW_TITLE:
        plotter.add_title(
            "n=4 advantage-space cross-section\n"
            f"normal={tuple(np.asarray(SLICE_NORMAL, dtype=float))}, "
            f"offset={SLICE_OFFSET:g}  ({slice_equation_label(normal, offset)})",
            font_size=11,
        )

    if SHOW_LEGEND:
        plotter.add_legend()

    # Configure the camera BEFORE creating the inset, because the inset
    # position is defined in camera-relative screen directions.
    configure_camera(plotter)

    if SHOW_AXIS_INSET:
        add_axis_inset(plotter, normal, basis)

    if SCREENSHOT:
        plotter.show(screenshot=SCREENSHOT)
    else:
        plotter.show()


# ============================================================================
# MAIN
# ============================================================================

def main() -> None:
    log("Building n=4 RAC geometry...")

    vertices = build_vertices()

    log(f"      generated {len(vertices)} unique 4D points")
    log("")

    normal = np.asarray(SLICE_NORMAL, dtype=float)
    norm = np.linalg.norm(normal)

    if norm < TOL:
        raise ValueError("SLICE_NORMAL cannot be zero.")

    # Normalize the plane equation so multiplying SLICE_NORMAL by a scalar
    # does not change the geometric plane.
    normal = normal / norm
    offset = float(SLICE_OFFSET) / norm

    points3, points4, basis, hull3 = compute_section(
        vertices,
        normal,
        offset,
    )

    x0 = offset * normal

    log("")
    log("Slice basis vectors expressed in (c1,c2,c3,c4):")

    for i in range(3):
        log(f"  axis {i + 1}: {np.round(basis[:, i], 5)}")

    if PRINT_SECTION_VERTICES:
        log("")
        log("Section vertices in original (c1,c2,c3,c4) coordinates:")

        for point in points4:
            log(f"  {np.round(point, 6)}")

    log("")
    log("Rendering settings:")
    log(f"  opacity        = {OPACITY}")
    log("  edges          = reconstructed from merged coplanar faces")
    log(f"  plane tolerance = normal {COPLANAR_NORMAL_TOL:g}, offset {COPLANAR_OFFSET_TOL:g}")
    log(f"  camera         = {CAMERA_POSITION}")
    log(f"  axis inset     = right {AXIS_INSET_RIGHT}, up {AXIS_INSET_UP}")
    log(f"  key light      = {LIGHT_POSITION}")
    log(
        f"  fill light     = "
        f"{FILL_LIGHT_POSITION if USE_FILL_LIGHT else 'disabled'}"
    )
    log("")

    plot_section(points3, hull3, vertices, normal, offset, x0, basis)


if __name__ == "__main__":
    main()